#!/usr/bin/env bash
usage() {
  cat <<'USAGE'
Usage:
  ./deploy.sh path/to/project

Description:
  Builds the QHTML release bundle and copies deploy artifacts into:
    path/to/project/qhtml
USAGE
}

if [[ $# -ne 1 ]]; then
  usage
  exit 1
fi

PROJECT_ARG="$1"
if [[ ! -d "$PROJECT_ARG" ]]; then
  echo "Error: project path does not exist or is not a directory: $PROJECT_ARG" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="$SCRIPT_DIR/dist"
TOOLS_DIR="$SCRIPT_DIR/tools"
PROJECT_ROOT="$(cd "$PROJECT_ARG" && pwd)"
TARGET_DIR="$PROJECT_ROOT/qhtml"
TARGET_COMPONENTS_DIR="$TARGET_DIR/q-components"
TARGET_COMPONENTS_BUNDLE="$TARGET_DIR/q-components.qhtml"
DIST_COMPONENTS_DIR="$DIST_DIR/q-components"
DIST_COMPONENTS_BUNDLE="$DIST_DIR/q-components.qhtml"

if [[ ! -d "$DIST_DIR" ]]; then
  echo "Error: dist directory not found at $DIST_DIR" >&2
  exit 1
fi

# Capture pre-existing state before mkdir creates deployment paths.
HAD_TARGET_COMPONENTS_DIR=0
HAD_TARGET_COMPONENTS_BUNDLE=0
[[ -d "$TARGET_COMPONENTS_DIR" ]] && HAD_TARGET_COMPONENTS_DIR=1
[[ -f "$TARGET_COMPONENTS_BUNDLE" ]] && HAD_TARGET_COMPONENTS_BUNDLE=1

echo "Building release bundle..."
if [[ -x "$SCRIPT_DIR/src/build-release.sh" ]]; then
  (
    cd "$SCRIPT_DIR"
    ./src/build-release.sh
  )
elif [[ -x "$SCRIPT_DIR/build-release.sh" ]]; then
  (
    cd "$SCRIPT_DIR"
    ./build-release.sh
  )
else
  echo "Error: could not find an executable build-release.sh script." >&2
  exit 1
fi

mkdir -p "$TARGET_DIR"
mkdir -p "$TARGET_COMPONENTS_DIR"
mkdir -p "$TARGET_DIR/codemirror"

ask_yes_no() {
  local prompt="$1"
  local default_answer="${2:-n}"
  local suffix="[y/N]"
  local answer

  case "$default_answer" in
    y|Y|yes|YES) suffix="[Y/n]" ;;
    *) suffix="[y/N]" ;;
  esac

  read -r -p "$prompt $suffix " answer
  answer="$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')"

  if [[ -z "$answer" ]]; then
    answer="$(printf '%s' "$default_answer" | tr '[:upper:]' '[:lower:]')"
  fi

  [[ "$answer" == "y" || "$answer" == "yes" ]]
}

copy_if_exists() {
  local src="$1"
  local dst="$2"
  if [[ -e "$src" ]]; then
    cp -f "$src" "$dst"
    echo "Copied: $src -> $dst"
  else
    echo "Warning: missing file: $src" >&2
  fi
}

copy_glob_files() {
  local pattern="$1"
  local dst="$2"
  shopt -s nullglob
  local files=( $pattern )
  shopt -u nullglob
  if (( ${#files[@]} == 0 )); then
    echo "Warning: no matches for pattern: $pattern" >&2
    return
  fi
  local f
  for f in "${files[@]}"; do
    cp -f "$f" "$dst"
    echo "Copied: $f -> $dst"
  done
}

copy_q_components_files() {
  if [[ ! -d "$DIST_COMPONENTS_DIR" ]]; then
    echo "Warning: missing directory: $DIST_COMPONENTS_DIR" >&2
    return
  fi

  copy_glob_files "$DIST_COMPONENTS_DIR/*.qhtml" "$TARGET_COMPONENTS_DIR/"
}

merge_q_components_bundle() {
  local src_dir="$1"
  local dst_file="$2"
  local tmp_file

  if [[ ! -d "$src_dir" ]]; then
    echo "Warning: cannot merge q-components; directory does not exist: $src_dir" >&2
    return 1
  fi

  shopt -s nullglob
  local files=( "$src_dir"/*.qhtml )
  shopt -u nullglob

  if (( ${#files[@]} == 0 )); then
    echo "Warning: cannot merge q-components; no .qhtml files found in: $src_dir" >&2
    return 1
  fi

  tmp_file="$(mktemp)"

  {
    echo "/*"
    echo "  Auto-generated by deploy.sh."
    echo "  Source directory: $src_dir"
    echo "  Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "*/"
    echo

    local f
    for f in "${files[@]}"; do
      echo "/* ========================================================= */"
      echo "/* Component file: $(basename "$f") */"
      echo "/* ========================================================= */"
      echo
      cat "$f"
      echo
      echo
    done
  } > "$tmp_file"

  mv -f "$tmp_file" "$dst_file"
  echo "Merged ${#files[@]} q-component files -> $dst_file"
}

deploy_q_components() {
  local overwrite_components="yes"

  if (( HAD_TARGET_COMPONENTS_DIR == 1 && HAD_TARGET_COMPONENTS_BUNDLE == 1 )); then
    echo
    echo "Existing q-components deployment detected:"
    echo "  Folder: $TARGET_COMPONENTS_DIR"
    echo "  Bundle: $TARGET_COMPONENTS_BUNDLE"
    echo

    if ask_yes_no "Overwrite files in the project's q-components folder from dist/q-components?" "n"; then
      overwrite_components="yes"
    else
      overwrite_components="no"
      echo "Skipped copying q-components/*.qhtml into: $TARGET_COMPONENTS_DIR"
    fi
  fi

  if [[ "$overwrite_components" == "yes" ]]; then
    copy_q_components_files
  fi

  echo
  if ask_yes_no "Merge q-components/*.qhtml into q-components.qhtml to reduce import requests?" "y"; then
    merge_q_components_bundle "$TARGET_COMPONENTS_DIR" "$TARGET_COMPONENTS_BUNDLE" || true
    return
  fi

  if [[ -f "$TARGET_COMPONENTS_BUNDLE" ]]; then
    if ask_yes_no "Replace existing q-components.qhtml with dist/q-components.qhtml?" "n"; then
      copy_if_exists "$DIST_COMPONENTS_BUNDLE" "$TARGET_DIR/"
    else
      echo "Skipped q-components.qhtml replacement: $TARGET_COMPONENTS_BUNDLE"
    fi
  else
    copy_if_exists "$DIST_COMPONENTS_BUNDLE" "$TARGET_DIR/"
  fi
}

# Required core files
copy_if_exists "$DIST_DIR/qhtml.js" "$TARGET_DIR/"
copy_if_exists "$DIST_DIR/w3.qhtml" "$TARGET_DIR/"

# q-components module files and aggregate bundle
#
# Behavior:
#   1. If the target already has q-components/ and q-components.qhtml, ask before
#      overwriting q-components/*.qhtml in the project path.
#   2. Ask whether to merge target q-components/*.qhtml into q-components.qhtml.
#   3. If not merging, ask before replacing an existing q-components.qhtml with
#      the repo dist/q-components.qhtml file.
deploy_q_components

# CSS and HTML assets
copy_glob_files "$DIST_DIR/*.css" "$TARGET_DIR/"
copy_glob_files "$DIST_DIR/*.html" "$TARGET_DIR/"

# codemirror assets
if [[ -d "$TOOLS_DIR/codemirror" ]]; then
  cp -Rf "$TOOLS_DIR/codemirror/." "$TARGET_DIR/codemirror/"
  echo "Copied: $TOOLS_DIR/codemirror/* -> $TARGET_DIR/codemirror/"
else
  echo "Warning: missing directory: $TOOLS_DIR/codemirror" >&2
fi

# Extra JS helpers
copy_if_exists "$TOOLS_DIR/q-editor.js" "$TARGET_DIR/"
copy_if_exists "$DIST_DIR/w3.css" "$TARGET_DIR/"

echo
echo "Deploy copy complete."
echo "Project root: $PROJECT_ROOT"
echo "QHTML assets: $TARGET_DIR"
echo

read -r -p "Would you like to run a local HTTP server to test qhtml in the browser? [Y/n] " RUN_SERVER
RUN_SERVER="$(printf '%s' "$RUN_SERVER" | tr '[:upper:]' '[:lower:]')"

if [[ -z "$RUN_SERVER" || "$RUN_SERVER" == "y" || "$RUN_SERVER" == "yes" ]]; then
  echo "temporary web server running - open http://127.0.0.1:8000 in your browser"
  cd "$PROJECT_ROOT"
  if command -v python >/dev/null 2>&1; then
    python -m http.server 8000 --bind 127.0.0.1
  elif command -v python3 >/dev/null 2>&1; then
    python3 -m http.server 8000 --bind 127.0.0.1
  else
    echo "Error: neither python nor python3 is available on PATH." >&2
    exit 1
  fi
else
  echo "Done. Exiting without starting server."
fi
